version: '3.8'

services:
  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front_end:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back_end:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/zelij
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      - mongodb
      - minio

  mongodb:
    image: mongo:latest
    ports:
      - "27011:27017"
    volumes:
      - mongodb_data:/data/db

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9001" /data

volumes:
  mongodb_data:
  minio_data: